import { createHash } from 'node:crypto'
import { join } from 'node:path'

import {
  type AiInputBundle,
  type Event,
  type EventInput,
  EventWriter,
} from '@they-juanreina/compost-provenance'

/** Open an EventWriter on a seed's .compost/events.sqlite. */
export function openSeedEvents(seedPath: string): EventWriter {
  return new EventWriter({ dbPath: join(seedPath, '.compost', 'events.sqlite') })
}

/** Content-address an artifact's initial state (SHA256 of canonical JSON). */
export function artifactId(initialState: unknown): string {
  return createHash('sha256').update(JSON.stringify(initialState)).digest('hex')
}

/** Emit an agent-authored `create` event (used by ingest + ingest-watcher). */
export function emitAgentCreate(
  writer: EventWriter,
  params: {
    artifactKind: string
    initialState: Record<string, unknown>
    agentName: string
    agentVersion: string
    batchId?: string
    /** Reconstructable inputs to this (deterministic) operation. When provided,
     * persisted via recordInputs and linked as the event's input_id so the
     * artifact can be regenerated by `compost rerun`. */
    inputs?: AiInputBundle
  },
): Event {
  const input_id = params.inputs !== undefined ? writer.recordInputs(params.inputs) : undefined
  const input: EventInput = {
    artifact_kind: params.artifactKind,
    artifact_id: artifactId(params.initialState),
    action: 'create',
    actor_type: 'agent',
    actor_id: `${params.agentName}@${params.agentVersion}`,
    agent_name: params.agentName,
    agent_version: params.agentVersion,
    payload: params.initialState,
    ...(input_id !== undefined ? { input_id } : {}),
    ...(params.batchId !== undefined ? { batch_id: params.batchId } : {}),
  }
  return writer.appendEvent(input)
}

/**
 * Author of a researcher- or AI-created artifact. A direct CLI invocation is a
 * researcher; the MCP wrapper (Claude Code) passes `ai` with an actor_id like
 * `claude-code:<plugin_ver>:<sha256(prompt)[:8]>` and a prompt_hash so the
 * suggestion lands as `[draft]` until a researcher endorses it.
 */
export interface Author {
  actorType: 'researcher' | 'ai'
  actorId: string
  model?: string
  promptHash?: string
}

/** Emit a researcher- or AI-authored `create` event. artifact_id is the SHA256
 * of initialState (the provenance content-address); the human-facing file id
 * lives in initialState.id so blame can map between them. */
export function emitCreate(
  writer: EventWriter,
  params: {
    artifactKind: string
    initialState: Record<string, unknown>
    author: Author
    /** Best-effort captured inputs for an AI create (the host agent may pass them
     * via `compost create --inputs-file`). When provided, persisted and linked as
     * the event's input_id; absent → only prompt_hash survives, as before. */
    inputs?: AiInputBundle
  },
): Event {
  const { author } = params
  const input_id = params.inputs !== undefined ? writer.recordInputs(params.inputs) : undefined
  const input: EventInput = {
    artifact_kind: params.artifactKind,
    artifact_id: artifactId(params.initialState),
    action: 'create',
    actor_type: author.actorType,
    actor_id: author.actorId,
    payload: params.initialState,
    ...(author.model !== undefined ? { model: author.model } : {}),
    ...(author.promptHash !== undefined ? { prompt_hash: author.promptHash } : {}),
    ...(input_id !== undefined ? { input_id } : {}),
  }
  return writer.appendEvent(input)
}

/** Re-export so call sites can build bundles without importing the provenance
 * package directly. */
export type { AiInputBundle }

/** Emit a researcher `endorse` event chaining the artifact's create event.
 * Promotes an AI `[draft]` to endorsed (snapshot author becomes hybrid). */
export function emitEndorse(
  writer: EventWriter,
  params: {
    artifactKind: string
    artifactId: string
    parentEventId: string
    researcherId: string
  },
): Event {
  return writer.appendEvent({
    artifact_kind: params.artifactKind,
    artifact_id: params.artifactId,
    action: 'endorse',
    actor_type: 'researcher',
    actor_id: params.researcherId,
    parent_event: params.parentEventId,
    payload: { endorsed: true },
  })
}
