import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'

import { validateTranscript } from './validate.js'

// Cross-language contract guard: the CLI validator that the export / `compost
// validate seed` gates rely on must accept what the native transcriber actually
// emits. The fixture is a real run_pipeline output (parakeet/whisper + pyannote),
// regenerated by `transcriber/scripts/export_transcript_fixture.py`. Before the
// transcriber↔schema reconciliation it failed with ~700 errors: raw SPEAKER_NN
// ids, a non-schema `diarization` utterance key, typed CUE-OV- ids, and null
// provenance fields.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const FIXTURE = join(REPO_ROOT, 'transcriber', 'tests', 'fixtures', 'native_transcript.json')

describe('validateTranscript over native transcriber output', () => {
  it('accepts the committed native transcript fixture', () => {
    assert.ok(
      existsSync(FIXTURE),
      `missing fixture ${FIXTURE} — regenerate via \`python scripts/export_transcript_fixture.py\``,
    )
    const result = validateTranscript(FIXTURE)
    assert.equal(result.errors, null)
    assert.equal(result.ok, true)
  })
})
