"""Tests for the ffmpeg frame extractor (#14) and shot-change detector (#15).

Uses a synthetic 6s clip (red 0-3s, blue 3-6s) generated by a fixture so the
shot change at 3s is deterministic. Requires ffmpeg on PATH.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest
from PIL import Image

from app.frames import FrameTrigger, extract_frames, frame_id, sampling_triggers
from app.shot_change import detect_shot_changes

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not on PATH")


@pytest.fixture
def clip(tmp_path: Path) -> Path:
    # Two structurally-distinct test patterns (testsrc → testsrc2) so the cut at
    # 3s produces a large perceptual-hash distance, like a real scene change.
    # (Solid colors all share a near-identical flat pHash, which is why we use
    # patterned sources here.)
    out = tmp_path / "clip.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc=s=320x180:d=3:r=10",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=s=320x180:d=3:r=10",
            "-filter_complex",
            "[0:v][1:v]concat=n=2:v=1:a=0",
            str(out),
        ],
        capture_output=True,
        check=True,
    )
    return out


def test_extract_one_frame_per_trigger_at_640x360(clip: Path, tmp_path: Path):
    seed = tmp_path / "seed"
    triggers = [
        FrameTrigger(at_ms=1000, trigger="sampling"),
        FrameTrigger(at_ms=4000, trigger="silence_thinking", linked_utterance_id="U-0007"),
    ]
    frames = extract_frames(clip, "S001", triggers, seed)
    assert len(frames) == 2
    for f in frames:
        jpg = seed / f["path"]
        assert jpg.exists()
        with Image.open(jpg) as img:
            assert img.size == (640, 360)
    # linked id preserved only where provided
    assert frames[1]["linked_utterance_id"] == "U-0007"
    assert "linked_utterance_id" not in frames[0]


def test_frame_index_entry_shape(clip: Path, tmp_path: Path):
    seed = tmp_path / "seed"
    frames = extract_frames(clip, "S001", [FrameTrigger(at_ms=2000, trigger="manual")], seed)
    f = frames[0]
    assert f["id"] == frame_id(2000)
    assert f["at_ms"] == 2000
    assert f["trigger"] == "manual"
    assert f["path"] == "sessions/S001/frames/000002000.jpg"


def test_idempotent_rerun_does_not_duplicate(clip: Path, tmp_path: Path):
    seed = tmp_path / "seed"
    triggers = [FrameTrigger(at_ms=1500, trigger="sampling")]
    extract_frames(clip, "S001", triggers, seed)
    jpg = seed / "sessions/S001/frames/000001500.jpg"
    mtime1 = jpg.stat().st_mtime_ns
    # second run: file should not be rewritten
    frames2 = extract_frames(clip, "S001", triggers, seed)
    assert len(frames2) == 1
    assert jpg.stat().st_mtime_ns == mtime1


def test_dedupes_triggers_at_same_ms(clip: Path, tmp_path: Path):
    seed = tmp_path / "seed"
    triggers = [
        FrameTrigger(at_ms=1000, trigger="silence_thinking"),
        FrameTrigger(at_ms=1000, trigger="audio_cue"),  # same ms
    ]
    frames = extract_frames(clip, "S001", triggers, seed)
    assert len(frames) == 1


def test_sampling_only_fills_uncovered_windows():
    # duration 180s, existing triggers at 10s and 130s
    triggers = sampling_triggers(180_000, existing_ms=[10_000, 130_000], interval_s=60)
    sampled_ms = [t.at_ms for t in triggers]
    # window [0,60k) covered by 10k; [60k,120k) uncovered → 60k; [120k,180k) covered by 130k
    assert sampled_ms == [60_000]
    assert all(t.trigger == "sampling" for t in triggers)


def test_detect_shot_change_at_three_seconds(clip: Path):
    changes = detect_shot_changes(clip, duration_ms=6000, sample_interval_ms=500)
    # the red→blue cut is at 3000ms; allow ±500ms (one sample window)
    assert any(abs(ms - 3000) <= 500 for ms in changes), f"no shot change near 3s: {changes}"


def test_no_false_positive_on_static_clip(tmp_path: Path):
    static = tmp_path / "static.mp4"
    subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=green:s=320x180:d=4", str(static)],
        capture_output=True,
        check=True,
    )
    changes = detect_shot_changes(static, duration_ms=4000, sample_interval_ms=500)
    assert changes == []
