import { existsSync } from 'node:fs'

import Database from 'better-sqlite3'

import { CompostError } from '../errors.js'

/**
 * W3C PROV export of a seed's event log, as JSON-LD, using the PROV-AGENT
 * vocabulary (arXiv:2508.02866) for the AI/agent specifics.
 *
 * Base PROV:
 *   artifact            → prov:Entity
 *   event/action        → prov:Activity (prov:generated / prov:used)
 *   actor               → prov:Agent (researcher=prov:Person; agent/ai=prov:SoftwareAgent)
 *   parent_event        → prov:wasInformedBy
 *
 * PROV-AGENT extensions:
 *   ai actor            → provagent:AIAgent
 *   ai event            → provagent:AIModelInvocation (an Activity)
 *   model               → provagent:AIModel (Entity, prov:used by the invocation)
 *   ai input bundle     → provagent:Prompt (Entity, prov:used by the invocation)
 *   ai-generated artifact → provagent:ResponseData
 *   agent name@version  → provagent:AgentTool (Entity, prov:used by an agent Activity)
 *
 * Because §1 persists inputs, an AI invocation expresses its real prov:used Prompt
 * + AIModel instead of only an opaque prompt_hash.
 */

interface EventRow {
  id: string
  ts: string
  artifact_kind: string
  artifact_id: string
  action: string
  actor_type: string
  actor_id: string
  agent_name: string | null
  agent_version: string | null
  model: string | null
  input_id: string | null
  parent_event: string | null
}

export interface ProvExport {
  document: Record<string, unknown>
  entities: number
  activities: number
  agents: number
  inputs: number
  models: number
  tools: number
}

const CONTEXT = {
  prov: 'http://www.w3.org/ns/prov#',
  compost: 'https://compost.dev/prov#',
  provagent: 'https://compost.dev/prov-agent#',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
}

const ART = (id: string) => `compost:artifact/${id}`
const EVT = (id: string) => `compost:event/${id}`
const AGENT = (id: string) => `compost:agent/${encodeURIComponent(id)}`
const INPUT = (id: string) => `compost:input/${id}`
const MODEL = (m: string) => `compost:model/${encodeURIComponent(m)}`
const TOOL = (id: string) => `compost:tool/${encodeURIComponent(id)}`

function agentTypes(actorType: string): string[] {
  if (actorType === 'researcher') return ['prov:Agent', 'prov:Person']
  if (actorType === 'ai') return ['prov:Agent', 'prov:SoftwareAgent', 'provagent:AIAgent']
  return ['prov:Agent', 'prov:SoftwareAgent'] // agent
}

export function eventsToProvO(eventsDbPath: string): ProvExport {
  if (!existsSync(eventsDbPath)) {
    throw new CompostError('FILE_NOT_FOUND', `No events.sqlite at ${eventsDbPath}`)
  }
  const db = new Database(eventsDbPath, { readonly: true, fileMustExist: true })
  let rows: EventRow[]
  try {
    rows = db
      .prepare(
        'SELECT id, ts, artifact_kind, artifact_id, action, actor_type, actor_id, agent_name, agent_version, model, input_id, parent_event FROM events ORDER BY ts, rowid',
      )
      .all() as EventRow[]
  } finally {
    db.close()
  }

  const graph: Array<Record<string, unknown>> = []
  const artifacts = new Map<string, string>() // artifact_id → kind
  const agents = new Map<string, string>() // actor_id → actor_type
  const inputs = new Set<string>()
  const promptInputs = new Set<string>() // input bundles used by ai invocations
  const aiArtifacts = new Set<string>() // artifacts generated by an ai invocation
  const models = new Set<string>()
  const tools = new Map<string, { name: string | null; version: string | null }>()

  for (const e of rows) {
    if (!artifacts.has(e.artifact_id)) artifacts.set(e.artifact_id, e.artifact_kind)
    if (!agents.has(e.actor_id)) agents.set(e.actor_id, e.actor_type)
    if (e.input_id !== null) {
      inputs.add(e.input_id)
      if (e.actor_type === 'ai') promptInputs.add(e.input_id)
    }
    if (e.model !== null) models.add(e.model)
    if (e.actor_type === 'agent')
      tools.set(e.actor_id, { name: e.agent_name, version: e.agent_version })
    const generates = e.action === 'create' || e.action === 'link'
    if (generates && e.actor_type === 'ai') aiArtifacts.add(e.artifact_id)

    const types =
      e.actor_type === 'ai' ? ['prov:Activity', 'provagent:AIModelInvocation'] : 'prov:Activity'
    const activity: Record<string, unknown> = {
      '@id': EVT(e.id),
      '@type': types,
      'prov:startedAtTime': { '@value': e.ts, '@type': 'xsd:dateTime' },
      'prov:wasAssociatedWith': { '@id': AGENT(e.actor_id) },
      'compost:action': e.action,
      'compost:artifactKind': e.artifact_kind,
    }
    // create/link generate the entity; other actions use it.
    const used: Array<{ '@id': string }> = []
    if (generates) {
      activity['prov:generated'] = { '@id': ART(e.artifact_id) }
    } else {
      used.push({ '@id': ART(e.artifact_id) })
    }
    if (e.input_id !== null) used.push({ '@id': INPUT(e.input_id) })
    if (e.actor_type === 'ai' && e.model !== null) used.push({ '@id': MODEL(e.model) })
    if (e.actor_type === 'agent') used.push({ '@id': TOOL(e.actor_id) })
    if (used.length === 1) activity['prov:used'] = used[0]
    else if (used.length > 1) activity['prov:used'] = used
    if (e.parent_event !== null) activity['prov:wasInformedBy'] = { '@id': EVT(e.parent_event) }
    if (e.model !== null) activity['compost:model'] = e.model
    graph.push(activity)
  }

  // Entities (artifacts). ai-generated artifacts are also provagent:ResponseData.
  for (const [artifactId, kind] of artifacts) {
    graph.push({
      '@id': ART(artifactId),
      '@type': aiArtifacts.has(artifactId)
        ? ['prov:Entity', 'provagent:ResponseData']
        : 'prov:Entity',
      'compost:kind': kind,
      'compost:contentAddress': artifactId,
    })
  }
  // Agents.
  for (const [actorId, actorType] of agents) {
    graph.push({
      '@id': AGENT(actorId),
      '@type': agentTypes(actorType),
      'compost:actorType': actorType,
      'compost:actorId': actorId,
    })
  }
  // Input bundles. Those used by ai invocations are provagent:Prompt.
  for (const inputId of inputs) {
    graph.push({
      '@id': INPUT(inputId),
      '@type': promptInputs.has(inputId) ? ['prov:Entity', 'provagent:Prompt'] : 'prov:Entity',
      'compost:kind': 'ai_input_bundle',
      'compost:contentAddress': inputId,
    })
  }
  // AI models referenced.
  for (const model of models) {
    graph.push({
      '@id': MODEL(model),
      '@type': ['prov:Entity', 'provagent:AIModel'],
      'compost:model': model,
    })
  }
  // Agent tools (deterministic software actors invoked as tools).
  for (const [actorId, meta] of tools) {
    graph.push({
      '@id': TOOL(actorId),
      '@type': ['prov:Entity', 'provagent:AgentTool'],
      'compost:agentName': meta.name,
      'compost:agentVersion': meta.version,
    })
  }

  return {
    document: { '@context': CONTEXT, '@graph': graph },
    entities: artifacts.size,
    activities: rows.length,
    agents: agents.size,
    inputs: inputs.size,
    models: models.size,
    tools: tools.size,
  }
}
